name: Release Helm Chart

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build_bench:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Helm deploy key
        if: github.repository == 'naderelabed/helm'
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HELM_DEPLOY_KEY }}
      - name: Setup Git Credentials
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Install Chartpress
        run: pip3 install chartpress
      - name: Publish Chart
        run: chartpress --publish-chart
